In [1]:
from sklearn.datasets import load_iris

In [2]:
iris=load_iris()

In [3]:
X=iris.data
y=iris.target

In [4]:
print X.shape
print y.shape

(150L, 4L)
(150L,)


In [7]:
import pandas as pd
pd.DataFrame(X,columns=iris.feature_names).head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [8]:
print y

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [9]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()

In [10]:
knn.fit(X,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [11]:
knn.predict([[3,5,4,2]])

array([1])

In [15]:
###Representing Text as Numerical Data

In [12]:
simple_train = ['call you tonight', 'Call me a cab', 'please call me... PLEASE!']

In [13]:
from sklearn.feature_extraction.text import CountVectorizer

In [15]:
vect =CountVectorizer()

In [18]:
vect.fit(simple_train)

CountVectorizer(analyzer=u'word', binary=False, decode_error=u'strict',
        dtype=<type 'numpy.int64'>, encoding=u'utf-8', input=u'content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern=u'(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [19]:
vect.get_feature_names()

[u'cab', u'call', u'me', u'please', u'tonight', u'you']

In [20]:
simple_train_dtm=vect.transform(simple_train)
simple_train_dtm

<3x6 sparse matrix of type '<type 'numpy.int64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [21]:
simple_train_dtm.toarray()

array([[0, 1, 0, 0, 1, 1],
       [1, 1, 1, 0, 0, 0],
       [0, 1, 1, 2, 0, 0]], dtype=int64)

In [22]:
pd.DataFrame(simple_train_dtm.toarray(),columns=vect.get_feature_names())

cab  call  me  please  tonight  you
0    0     1   0       0        1    1
1    1     1   1       0        0    0
2    0     1   1       2        0    0

In [23]:
type(simple_train_dtm)

scipy.sparse.csr.csr_matrix

In [24]:
print simple_train_dtm

  (0, 1)	1
  (0, 4)	1
  (0, 5)	1
  (1, 0)	1
  (1, 1)	1
  (1, 2)	1
  (2, 1)	1
  (2, 2)	1
  (2, 3)	2


In [25]:
simple_test=["please don't call me"]

In [26]:
simple_test_dtm=vect.transform(simple_test)

In [27]:
simple_test_dtm.toarray()

array([[0, 1, 1, 1, 0, 0]], dtype=int64)

In [28]:
pd.DataFrame(simple_test_dtm.toarray(),columns=vect.get_feature_names())

cab  call  me  please  tonight  you
0    0     1   1       1        0    0

In [29]:
url = 'https://raw.githubusercontent.com/justmarkham/pycon-2016-tutorial/master/data/sms.tsv'
sms = pd.read_csv(url, header=None, names=['label', 'message'],sep='\t')

In [30]:
sms.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [31]:
sms.shape

(5572, 2)

In [32]:
sms.label.value_counts()

ham     4825
spam     747
Name: label, dtype: int64

In [33]:
sms["lbl_num"]=sms.label.map({'ham':0,'spam':1})

In [34]:
sms.head()

label                                            message  lbl_num
0   ham  Go until jurong point, crazy.. Available only ...        0
1   ham                      Ok lar... Joking wif u oni...        0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        1
3   ham  U dun say so early hor... U c already then say...        0
4   ham  Nah I don't think he goes to usf, he lives aro...        0

In [35]:
X=sms.message
y=sms.lbl_num
print X.shape
print y.shape

(5572L,)
(5572L,)


In [37]:
from sklearn.cross_validation import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=1)
print X_train.shape
print X_test.shape
print y_train.shape
print y_test.shape

(4179L,)
(1393L,)
(4179L,)
(1393L,)


In [38]:
vect=CountVectorizer()
vect.fit(X_train)
X_train_dtm=vect.transform(X_train)
X_train_dtm

<4179x7456 sparse matrix of type '<type 'numpy.int64'>'
	with 55209 stored elements in Compressed Sparse Row format>

In [39]:
X_test_dtm=vect.transform(X_test)
X_test_dtm

<1393x7456 sparse matrix of type '<type 'numpy.int64'>'
	with 17604 stored elements in Compressed Sparse Row format>

In [40]:
from sklearn.naive_bayes import MultinomialNB
nb=MultinomialNB()

In [41]:
%time nb.fit(X_train_dtm,y_train)

Wall time: 165 ms


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [42]:
y_pred_class=nb.predict(X_test_dtm)

In [44]:
from sklearn import metrics
metrics.accuracy_score(y_test,y_pred_class)


0.98851399856424982

In [45]:
metrics.confusion_matrix(y_test,y_pred_class)

array([[1203,    5],
       [  11,  174]])

In [46]:
X_test[y_test<y_pred_class]

574               Waiting for your call.
3375             Also andros ice etc etc
45      No calls..messages..missed calls
3415             No pic. Please re-send.
1988    No calls..messages..missed calls
Name: message, dtype: object

In [47]:
X_test[y_test>y_pred_class]

3132    LookAtMe!: Thanks for your purchase of a video...
5       FreeMsg Hey there darling it's been 3 week's n...
3530    Xmas & New Years Eve tickets are now on sale f...
684     Hi I'm sue. I am 20 years old and work as a la...
1875    Would you like to see my XXX pics they are so ...
1893    CALL 09090900040 & LISTEN TO EXTREME DIRTY LIV...
4298    thesmszone.com lets you send free anonymous an...
4949    Hi this is Amy, we will be sending you a free ...
2821    INTERFLORA - “It's not too late to order Inter...
2247    Hi ya babe x u 4goten bout me?' scammers getti...
4514    Money i have won wining number 946 wot do i do...
Name: message, dtype: object

In [48]:
metrics.roc_auc_score(y_test,y_pred_class)

0.96820073384642935

In [49]:
#comparing Models

In [50]:
from sklearn.linear_model import LogisticRegression
logreg=LogisticRegression()

In [51]:
%time logreg.fit(X_train_dtm,y_train)

Wall time: 515 ms


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [52]:
y_pred_class=logreg.predict(X_test_dtm)

In [53]:
metrics.accuracy_score(y_test,y_pred_class)

0.9877961234745154

In [55]:
metrics.roc_auc_score(y_test,y_pred_class)

0.95634284947198855

In [56]:
###Examining the model

In [57]:
X_train_tokens=vect.get_feature_names()
len(X_train_tokens)

7456

In [58]:
nb.feature_count_

array([[  0.,   0.,   0., ...,   1.,   1.,   1.],
       [  5.,  23.,   2., ...,   0.,   0.,   0.]])

In [59]:
nb.feature_count_.shape

(2L, 7456L)

In [60]:
ham_token_count=nb.feature_count_[0,:]
spam_token_count=nb.feature_count_[1,:]
print ham_token_count
print spam_token_count

[ 0.  0.  0. ...,  1.  1.  1.]
[  5.  23.   2. ...,   0.   0.   0.]


In [61]:
tokens=pd.DataFrame({'token':X_train_tokens,'ham':ham_token_count,'spam':spam_token_count}).set_index('token')
tokens.head()

ham  spam
token                  
00            0.0   5.0
000           0.0  23.0
008704050406  0.0   2.0
0121          0.0   1.0
01223585236   0.0   1.0

In [62]:
tokens.sample(5,random_state=6)

ham  spam
token                   
very          64.0   2.0
nasty          1.0   1.0
villa          0.0   1.0
beloved        1.0   0.0
textoperator   0.0   2.0

In [63]:
nb.class_count_

array([ 3617.,   562.])

In [64]:
tokens['ham']=tokens.ham+1
tokens['spam']=tokens.spam+1
tokens.sample(5,random_state=6)

ham  spam
token                   
very          65.0   3.0
nasty          2.0   2.0
villa          1.0   2.0
beloved        2.0   1.0
textoperator   1.0   3.0

In [66]:
tokens['spam_ratio']=tokens.spam/(tokens.ham+tokens.spam)
tokens.sample(5,random_state=6)

ham  spam  spam_ratio
token                               
very          65.0   3.0    0.044118
nasty          2.0   2.0    0.500000
villa          1.0   2.0    0.666667
beloved        2.0   1.0    0.333333
textoperator   1.0   3.0    0.750000

In [67]:
tokens.sort_values('spam_ratio',ascending=False)

ham  spam  spam_ratio
token                              
claim         1.0  89.0    0.988889
prize         1.0  76.0    0.987013
150p          1.0  49.0    0.980000
tone          1.0  48.0    0.979592
guaranteed    1.0  43.0    0.977273
18            1.0  39.0    0.975000
cs            1.0  37.0    0.973684
www           2.0  73.0    0.973333
1000          1.0  32.0    0.969697
awarded       1.0  30.0    0.967742
150ppm        1.0  29.0    0.966667
uk            2.0  56.0    0.965517
500           1.0  27.0    0.964286
ringtone      1.0  25.0    0.961538
mob           1.0  24.0    0.960000
000           1.0  24.0    0.960000
co            2.0  44.0    0.956522
collection    1.0  22.0    0.956522
valid         1.0  21.0    0.954545
2000          1.0  21.0    0.954545
800           1.0  21.0    0.954545
10p           1.0  21.0    0.954545
8007          1.0  20.0    0.952381
16            2.0  38.0    0.950000
weekly        1.0  19.0    0.950000
http          1.0  18.0    0.947368
tones         1.0  18.0    0.947368
land          1.0  18.0    0.947368
national      1.0  17.0    0.944444
5000          1.0  17.0    0.944444
...           ...   ...         ...
went         46.0   1.0    0.021277
ll          190.0   4.0    0.020619
told         50.0   1.0    0.019608
feel         50.0   1.0    0.019608
gud          51.0   1.0    0.019231
cos          54.0   1.0    0.018182
but         328.0   6.0    0.017964
amp          55.0   1.0    0.017857
sure         55.0   1.0    0.017857
something    55.0   1.0    0.017857
ok          221.0   4.0    0.017778
said         59.0   1.0    0.016667
morning      61.0   1.0    0.016129
yeah         64.0   1.0    0.015385
lol          64.0   1.0    0.015385
anything     65.0   1.0    0.015152
my          544.0   8.0    0.014493
doing        69.0   1.0    0.014286
ask          71.0   1.0    0.013889
already      71.0   1.0    0.013889
way          71.0   1.0    0.013889
too          79.0   1.0    0.012500
come        177.0   2.0    0.011173
later       111.0   1.0    0.008929
lor         119.0   1.0    0.008333
da          119.0   1.0    0.008333
she         129.0   1.0    0.007692
he          170.0   1.0    0.005848
lt          232.0   1.0    0.004292
gt          235.0   1.0    0.004237

[7456 rows x 3 columns]

In [69]:
tokens.loc['dating','spam_ratio']

0.9285714285714286